name: Release

on:
  workflow_dispatch:
    inputs:
      strategy:
        type: choice
        description: "Chose strategy"
        required: true
        default: 'Release'
        options:
          - Release

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'sbt'

      - name: Run release
        run: sbt "release with-defaults"
